import Head from 'next/head'
import React,{useState} from 'react';
import * as EmailValidator from 'email-validator';

export default function Home() {
  const [email,setEmail]=useState('');
  const [error,setError]=useState(false);

  const emailForm = event =>{
    event.preventDefault();
    const isValidEmail=EmailValidator.validate(email);
    if(!isValidEmail){
      setError(true);
      console.log('invalid');
    }
  };
  const emailOnChange = event =>{
    const {name,value}=event.target;
    setEmail(value);
    setError(false);
  }
  return (
    <div id="container">
      <Head>
        <title>Frontend Mentor | Base Apparel coming soon page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon-32x32.png" />
      </Head>
      <main id="main">
        <div id="logo-container">
          <img src="/images/logo.svg"/>
        </div>
        <div id="mobile-image-container">
          <img id="mobile-image" src="/images/hero-mobile.jpg"/>
        </div>
        <section>
          <div id="coming-soon-container">
            <div id="coming-soon"><span>We're</span><br/> coming<br/> soon</div>
          </div>
          <div id="content-container">
            <p id="content">
            Hello fellow shoppers! We're currently building our new fashion store. 
          Add your email below to stay up-to-date with announcements and our launch deals.
            </p>
          </div>
          <div id="form-container">
            <form id="form" onSubmit={emailForm} noValidate>
              <input id="input-email" className={error?"error-red-border":""} name="email" type="email" placeholder="Email Address" value={email} onChange={emailOnChange}/>
              <div id="error-container" className={error?"error show":"hide"}> <img src="/images/icon-error.svg"/> </div>
              <button id="btn" type="submit"><img src="/images/icon-arrow.svg"/></button>
            </form>
            <div id="error-msg" className={error?"show":"hide"}>Please provide a valid email</div>
          </div>
        </section>
        <footer>
          <p className="attribution">
            Challenge by <a href="https://www.frontendmentor.io?ref=challenge" target="_blank">Frontend Mentor</a>. 
            Coded by <a href="#">Angel Murillo</a>.
          </p>
        </footer>
      </main>
      <div id="image-container">
        <img id="image" src="/images/hero-desktop.jpg"/>
      </div>
    </div>
  )
}