import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div id="logo-container">
          <img src="/images/logo.svg"/>
        </div>
        <div id="mobile-image-container">
          <img id="mobile-image" id="mobile-image" src="/images/hero-mobile.jpg"/>
        </div>
        <section>
          <div id="coming-soon-container">
            <h1 id="coming-soon"><span>We're</span><br/> coming<br/> soon</h1>
          </div>
          <div id="content-container">
            <p id="content">
            Hello fellow shoppers! We're currently building our new fashion store. 
          Add your email below to stay up-to-date with announcements and our launch deals.
            </p>
          </div>
          <div id="form-container">
            <form>
              <input id="input-email" type="email"/>
              <button id="btn" type="submit"><img src="/images/icon-arrow.svg"/></button>
            </form>
          </div>
        </section>
      </main>
        <footer>
          <p className="attribution">
            Challenge by <a href="https://www.frontendmentor.io?ref=challenge" target="_blank">Frontend Mentor</a>. 
            Coded by <a href="#">Your Name Here</a>.
          </p>
        </footer>
        <style jsx>{
        `
        @import url('https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@300;400;600&display=swap');
          main{
            font-family: 'Josefin Sans', sans-serif;
            height:100%;
            display:flex;
            flex-direction:column;
            // overflow:none;
          }
          #logo-container{
            width:100%;
            padding: 15px 20px;
          }
          #mobile-image-container,#mobile-image{
            width:100%; height:100%;
          }
          section{
            background-image:url(./images/bg-pattern-desktop.svg);
            flex-grow:1;
          }
          #coming-soon-container{
            width:100%;
            text-transform: uppercase;
            text-align: center;
            padding:40px 0px 0px;
          }
          #coming-soon{
            font-size:32px;
          }
          #coming-soon span{
            color:hsl(0, 36%, 70%);
          }
          #content-container{
            width:100%;
          }
          #content{
            width:100%;
            text-align: center;
            padding: 0px 50px;
          }
          #form-container{
            display:flex;
            justify-content:center;
            align-items:center;
            padding:20px 0px 40px;
          }
          form{
            width:100%;
            position:relative;
            display:flex;
            justify-content:center;
          }
          #input-email{
            height:40px; width: 80%;
            border-radius: 5% / 50%;
            border:1px solid lightgray;
            background-color: rgba(0,0,0,0);
          }
          #btn{
            height:40px; width:55px;
            border:none;
            border-radius: 40% / 50%;
            background-image:
            linear-gradient(
              135deg, 
              hsl(0, 80%, 86%), hsl(0, 74%, 74%)
            );
            position: absolute;
            right:5%;
          }
          footer{
            // width:100%;
            margin-top:20px;
            display:flex;
            justify-content:center;
            align-items:center;
            font-size:10px;
          }
        `}
        </style>
    </div>
  )
}