import Head from 'next/head'
import Image from 'next/image'
import React,{useState} from 'react';
import styles from '../styles/Home.module.css'
import * as EmailValidator from 'email-validator';

export default function Home() {
  const [email,setEmail]=useState('');
  const [error,setError]=useState(false);
  const emailForm = event =>{
    event.preventDefault();
    const isValidEmail=EmailValidator.validate(email);
    if(!isValidEmail){
      setError(true);
      console.log('invalid');
    }
  };
  const emailOnChange = event =>{
    const {name,value}=event.target;
    setEmail(value);
    setError(false);
  }
  return (
    <div id="container" className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div id="logo-container">
          <img src="/images/logo.svg"/>
        </div>
        <div id="mobile-image-container">
          <img id="mobile-image" src="/images/hero-mobile.jpg"/>
        </div>
        <section>
          <div id="coming-soon-container">
            <div id="coming-soon"><span>We're</span><br/> coming<br/> soon</div>
          </div>
          <div id="content-container">
            <p id="content">
            Hello fellow shoppers! We're currently building our new fashion store. 
          Add your email below to stay up-to-date with announcements and our launch deals.
            </p>
          </div>
          <div id="form-container">
            <form onSubmit={emailForm} noValidate>
              <input id="input-email" name="email" type="email" placeholder="Email Address" value={email} onChange={emailOnChange}/>
              <div id="error-container" className="error hide"> <img src="/images/icon-error.svg"/> </div>
              <button id="btn" type="submit"><img src="/images/icon-arrow.svg"/></button>
            </form>
            <div id="error-msg" className={error?"show":"hide"}>Please provide a valid email</div>
          </div>
        </section>
        <footer>
          <p className="attribution">
            Challenge by <a href="https://www.frontendmentor.io?ref=challenge" target="_blank">Frontend Mentor</a>. 
            Coded by <a href="#">Your Name Here</a>.
          </p>
        </footer>
      </main>
      <div id="image-container">
        <img id="image" src="/images/hero-desktop.jpg"/>
      </div>
        
        <style jsx>{
        `
        @import url('https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@300;400;600&display=swap');
        .error{
          position:absolute;
          right:18%;
          top:15%;
        }
        .error-red-border{
          border:1px solid red;
        }
        .show{
          display:block;
        }
        .hide{
          display:none;
        }

        @media (max-width: 375px) {
            main{
              font-family: 'Josefin Sans', sans-serif;
              height:100%;
              display:flex;
              flex-direction:column;
            }
            #logo-container{
              width:100%;
              padding: 15px 20px;
            }
            #image-container,#image{
              width:100%; height:100%;
              display:none;
            }
            #mobile-image-container,#mobile-image{
              width:100%; height:100%;
            }
            section{
              background-image:url(./images/bg-pattern-desktop.svg);
              flex-grow:1;
            }
            #coming-soon-container{
              width:100%;
              text-transform: uppercase;
              text-align: center;
              padding:40px 0px 0px;
            }
            #coming-soon{
              font-size:32px;
            }
            #coming-soon span{
              color:hsl(0, 36%, 70%);
            }
            #content-container{
              width:100%;
            }
            #content{
              width:100%;
              text-align: center;
              padding: 0px 50px;
            }
            #form-container{
              display:flex;
              justify-content:center;
              align-items:center;
              padding:20px 0px 40px;
            }
            form{
              width:100%;
              position:relative;
              display:flex;
              justify-content:center;
            }
            #input-email{
              height:40px; width: 80%;
              border-radius: 5% / 50%;
              border:1px solid lightgray;
              background-color: rgba(0,0,0,0);
            }
            #btn{
              height:40px; width:55px;
              border:none;
              border-radius: 40% / 50%;
              background-image:
              linear-gradient(
                135deg, 
                hsl(0, 80%, 86%), hsl(0, 74%, 74%)
              );
              position: absolute;
              right:5%;
            }
            footer{
              // width:100%;
              margin-top:20px;
              display:flex;
              justify-content:center;
              align-items:center;
              font-size:10px;
            }
          }
          @media (min-width: 375px) {
            #container{
              display:flex;
            }
            #mobile-image-container{
              display:none;
            }
            main{
              font-family: 'Josefin Sans', sans-serif;
              padding:70px 22% 100px 8%;
              border:1px solid black;
            }
            #coming-soon-container{
              font-family: 'Josefin Sans', sans-serif;
              font-weight:400;
              letter-spacing: 24px;
              text-transform: uppercase;
              margin-top:80px;
              font-size:64px;
            }
            #coming-soon span{
              font-weight:300;
              color:hsl(0, 36%, 70%);
            }
            main{
              background-image:url(./images/bg-pattern-desktop.svg);
            }
            #image-container,#image{
              height:100%;
            }
            #content-container{
            }
            #content{
              font-weight:400;
              font-family: 'Josefin Sans', sans-serif;
              font-size:18px;
              line-height:40px;
            }
            form{
              width:100%;
              position:relative;
            }
            #input-email{
              height:40px; width: 95%;
              border-radius: 5% / 50%;
              border:1px solid lightgray;
              background-color: rgba(0,0,0,0);
              padding:18px;
            }
            #btn{
              height:40px; width:60px;
              border:none;
              border-radius: 40% / 50%;
              background-image:
              linear-gradient(
                135deg, 
                hsl(0, 80%, 86%), hsl(0, 74%, 74%)
              );
              position: absolute;
              right:3%;
            }
          }
        `}
        </style>
    </div>
  )
}